#!/bin/bash

# Use the Centos cloud repo to pull in its updated package lists
cat >/etc/yum.repos.d/CentOS-Cloud.repo <<EOF
[cloud]
name=CentOS-\$releasever - cloud
baseurl=http://cbs.centos.org/repos/cloud7-testing/\$basearch/os/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
EOF
