#!/bin/bash

set -eux
set -o pipefail

# Install repo file for Delorean master packages
# Even though these packages are for F20, we're still going to try and use them
# here since we don't yet have Delorean master el7 packages.
export DELOREAN_REPO=${DELOREAN_REPO:-"http://209.132.178.33/repos/current/delorean.repo"}
sudo curl -o /etc/yum.repos.d/delorean.repo $DELOREAN_REPO

# Install repo file for Delorean el7 midstream packages built from
# rdo-management.
export DELOREAN_RHEL7_REPO=${DELOREAN_RHEL7_REPO:-"http://ec2-52-1-152-252.compute-1.amazonaws.com/repos/current/delorean.repo"}
sudo curl -o /etc/yum.repos.d/delorean-rdo-management.repo $DELOREAN_RHEL7_REPO
# We can't have 2 yum repos called delorean though, so we must rename this one
sudo sed -i 's/delorean/delorean-rdo-management/' /etc/yum.repos.d/delorean-rdo-management.repo

# Delorean requires RDO
if ! rpm -q rdo-release; then
    sudo yum install -y https://rdo.fedorapeople.org/rdo-release.rpm
fi

if ! rpm -q epel-release; then
    sudo yum install -y http://mirrors.einstein.yu.edu/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
fi

# rhos-release is also required, otherwise we have no base RHEL repositories to
# pull any dependencies from (without using subscription-manager anyway).
sudo rpm -Uvh --force http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm
sudo rhos-release 6 -d
# Ideally though, we don't want to end up with any RHOS packages installed, so
# we disable the poodle repo.
sudo yum-config-manager --disable rhelosp-6.0-poodle

# Install some needed dependencies for instack-undercloud
sudo yum -y install \
    diskimage-builder \
    openstack-tripleo-image-elements \
    openstack-tripleo-heat-templates \
    openstack-tripleo \
    instack

sudo yum -y install git

# os-cloud-config is broken in Delorean packaging right now, b/c it's missing
# the patch to remove the pbr requirements, yet doesn't actually Require it, so
# just install it manually for now.
sudo yum -y install os-cloud-config
sudo yum -y install python-pbr

# tripleo-puppet-elements is not yet in Delorean, so just git clone for now
if [ ! -d "tripleo-puppet-elements" ]; then
    git clone http://git.openstack.org/openstack/tripleo-puppet-elements
else
    echo "WARNING##################################:"
    echo "tripleo-puppet-elements directory already exists, not recloning"
fi

# git clone instack-undercloud since we're not using packages for that yet
if [ ! -d "instack-undercloud" ]; then
    git clone http://github.com/rdo-management/instack-undercloud
else
    echo "WARNING##################################:"
    echo "instack-undercloud directory already exists, not recloning"
fi
