#!/bin/bash
set -eux
set -o pipefail

add-rule INPUT -p tcp --dport 8088 -j ACCEPT

[ -x /usr/sbin/semanage ] || exit 0
# Try to delete port if present
semanage port -d -t http_port_t -p tcp 8088 || true

# Add port
semanage port -a -t http_port_t -p tcp 8088
