#!/bin/bash
set -eux
set -o pipefail

add-rule INPUT -p tcp --dport 8089 -j ACCEPT

# Create the apache vHOST for Ironic Discoverd
mkdir -p /etc/httpd/conf.d
sudo cp -r $(dirname $0)/ironic-discoverd-vhost.template /etc/httpd/conf.d/10-ironic_discoverd_vhost.conf
sed -i /etc/httpd/conf.d/10-ironic_discoverd_vhost.conf -e 's#{{ROOT}}#/httpboot#g' -e 's#{{PORT}}#8089#g'

os-svc-enable -n apache2
os-svc-restart -n apache2 || true

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t httpd_sys_content_t "/httpboot(/.*)?"
restorecon -Rv /httpboot/

# Try to delete port if present
semanage port -d -t http_port_t -p tcp 8089 || true

# Add port
semanage port -a -t http_port_t -p tcp 8089
